### ISSUE TITLE
Problem with id.calendar_month_year_textview

### ISSUE THREAD

**Issue by locks** [roomorama/Caldroid#181]
Hello,

I am trying out Caldroid, but when I try to run the app on my device I get the following error:

```
11-13 17:15:57.006  26424-26424/com.locks.horrorison D/dalvikvm﹕ DexOpt: couldn't find static field Lcom/caldroid/R$id;.months_infinite_pager
11-13 17:15:57.006  26424-26424/com.locks.horrorison W/dalvikvm﹕ VFY: unable to resolve static field 4453 (months_infinite_pager) in Lcom/caldroid/R$id;
11-13 17:15:57.006  26424-26424/com.locks.horrorison D/dalvikvm﹕ VFY: replacing opcode 0x60 at 0x0147
11-13 17:15:57.016  26424-26424/com.locks.horrorison D/dalvikvm﹕ DexOpt: couldn't find static field Lcom/caldroid/R$id;.calendar_month_year_textview
11-13 17:15:57.016  26424-26424/com.locks.horrorison W/dalvikvm﹕ VFY: unable to resolve static field 4450 (calendar_month_year_textview) in Lcom/caldroid/R$id;
11-13 17:15:57.016  26424-26424/com.locks.horrorison D/dalvikvm﹕ VFY: replacing opcode 0x60 at 0x0014
11-13 17:15:57.020  26424-26424/com.locks.horrorison D/dalvikvm﹕ DexOpt: couldn't find static field Lcom/caldroid/R$id;.calendar_left_arrow
11-13 17:15:57.020  26424-26424/com.locks.horrorison I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x1161 at 0x1e in Lcom/roomorama/caldroid/CaldroidFragment;.onCreateView
11-13 17:15:57.020  26424-26424/com.locks.horrorison D/dalvikvm﹕ DexOpt: couldn't find static field Lcom/caldroid/R$id;.calendar_right_arrow
11-13 17:15:57.020  26424-26424/com.locks.horrorison I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x1163 at 0x28 in Lcom/roomorama/caldroid/CaldroidFragment;.onCreateView
11-13 17:15:57.021  26424-26424/com.locks.horrorison D/dalvikvm﹕ DexOpt: couldn't find static field Lcom/caldroid/R$id;.weekday_gridview
11-13 17:15:57.021  26424-26424/com.locks.horrorison I/dalvikvm﹕ DexOpt: unable to optimize static field ref 0x1166 at 0x4b in Lcom/roomorama/caldroid/CaldroidFragment;.onCreateView
11-13 17:15:57.047  26424-26424/com.locks.horrorison D/AndroidRuntime﹕ Shutting down VM
11-13 17:15:57.048  26424-26424/com.locks.horrorison W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41897d40)
11-13 17:15:57.052  26424-26424/com.locks.horrorison E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.locks.horrorison, PID: 26424
    java.lang.NoSuchFieldError: com.caldroid.R$id.calendar_month_year_textview
            at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1118)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1194)
            at android.app.Activity.performStart(Activity.java:5258)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

Here's my MainActivity and the relevant layout. If any information is missing please tell me so I can provide it, I'm very new to Android.
## MainActivity.java

```
package com.locks.horrorison;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.app.ActionBarActivity;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;

import com.roomorama.caldroid.CaldroidFragment;

import java.util.Calendar;

public class MainActivity extends FragmentActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        if (savedInstanceState == null) {
            getSupportFragmentManager().beginTransaction()
                    .add(R.id.container, new PlaceholderFragment())
                    .commit();
        }

        CaldroidFragment caldroidFragment = new CaldroidFragment();
        Bundle args = new Bundle();
        Calendar cal = Calendar.getInstance();
        args.putInt(CaldroidFragment.MONTH, cal.get(Calendar.MONTH) + 1);
        args.putInt(CaldroidFragment.YEAR, cal.get(Calendar.YEAR));
        caldroidFragment.setArguments(args);

        FragmentTransaction t = getSupportFragmentManager().beginTransaction();
        t.replace(R.id.calendar1, caldroidFragment);
        t.commit();
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    /**
     * A placeholder fragment containing a simple view.
     */
    public static class PlaceholderFragment extends Fragment {

        public PlaceholderFragment() {
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            View rootView = inflater.inflate(R.layout.fragment_main, container, false);
            return rootView;
        }
    }
}
```
## fragment_main.xml

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity$PlaceholderFragment">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <LinearLayout
            android:id="@+id/calendar1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical" >
        </LinearLayout>
    </LinearLayout>
</RelativeLayout>
```

**Comment by shrungBhatt** [comment]
I currently had this error. But my project was already developed and creating a new one was not a option.
So to solve this error what I did was, I imported the library:
**Project Structure -> Click + button -> Import new Project(One with gradle symbol)**
And select the project and import it.
After importing the project add **':caldroid'** in your settings.gradle and in the app gradle file add **implementation project(':caldroid')**
After this sync your project. After syncing the project in the caldroid folder change the name using **shift+f6** of the calender_view file in layout's folder.

Reason:
This error is caused when we use 2 layout files with identical resources. The android-studio is not able to map proper id's from 2 modules of the app.
