### ISSUE TITLE
public void moveToDate(Date date); show a error.

### ISSUE THREAD

**Issue by hanxuhui** [roomorama/Caldroid#204]
caldroidFragment.moveToDate(new Date());

error:12-29 09:36:26.649: E/AndroidRuntime(10186): Caused by: hirondelle.date4j.DateTime$ItemOutOfRange: Year is not in the range 1..9999. Value is:-1

**Comment by hanxuhui** [comment]
I want to jump to a date that i designated, not default today,but have a date4j's error.maybe my code put a error location.   code:
formatter = new SimpleDateFormat("yyyy-MM-dd");
Date date = formatter.parse("2015-2-16");
caldroidFragment.setSelectedDates(date, date);
caldroidFragment.moveToDate(date);

if you can fix it,please tell me.
forgive my poor english.

**Comment by antimoz89** [comment]
I couldn't reproduce the issue with above code even if I put it inside `onCreate()`. Could you please provide the full stack trace?

In the first post, it's certainly strange that `new Date()` returns invalid date with negative year (`-1`). In the next post, I didn't find any error, and Caldroid worked just expected.

**Comment by edryer** [comment]
Same error. This is definitely a bug.


03-01 02:25:31.172    7358-7358/com.design.application E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.design.application, PID: 7358
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.design.application/com.design.android.cal.ConcreteBookingsActivity}: hirondelle.date4j.DateTime$ItemOutOfRange: Year is not in the range 1..9999. Value is:-1
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: hirondelle.date4j.DateTime$ItemOutOfRange: Year is not in the range 1..9999. Value is:-1
            at hirondelle.date4j.DateTime.checkRange(DateTime.java:1538)
            at hirondelle.date4j.DateTime.validateState(DateTime.java:1525)
            at hirondelle.date4j.DateTime.<init>(DateTime.java:484)
            at com.roomorama.caldroid.CaldroidFragment.moveToDateTime(CaldroidFragment.java:542)
            at com.roomorama.caldroid.CaldroidFragment.moveToDate(CaldroidFragment.java:532)
            at com.design.android.cal.EventsMonthFragment.setMonthViewDate(EventsMonthFragment.java:500)
            at com.design.android.cal.EventsMonthFragment.onViewCreated(EventsMonthFragment.java:112)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:961)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5241)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method) bug.

**Comment by thomasdao** [comment]
The documented way to provide initial month is using a bundle. Attempting to call `moveToDate` when the fragment is not yet fully inflated will result in exception.

```java
CaldroidFragment caldroidFragment = new CaldroidFragment();
Bundle args = new Bundle();
Calendar cal = Calendar.getInstance();
args.putInt(CaldroidFragment.MONTH, 10); // October
args.putInt(CaldroidFragment.YEAR, 2015);
caldroidFragment.setArguments(args);

FragmentTransaction t = getSupportFragmentManager().beginTransaction();
t.replace(R.id.calendar1, caldroidFragment);
t.commit();
```

**Comment by hanxuhui** [comment]
you are right, thanks.
