### ISSUE TITLE
Issue when using library with ActionBarActivity in Android Studio (using gradle)

### ISSUE THREAD

**Issue by jitendrajain** [roomorama/Caldroid#240]
Error: You need to use a Theme.AppCompat theme (or descendant) with this activity.

LogCat:
03-17 16:39:37.051  23312-23312/com.iuconnect.iuconnectpro E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.iuconnect.iuconnectpro, PID: 23312
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iuconnect.iuconnectpro/com.iuconnect.iuconnectpro.activities.HomeActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
            at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:151)
            at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:138)
            at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
            at com.iuconnect.iuconnectpro.activities.ActionBarBaseActivity.onCreate(ActionBarBaseActivity.java:21)
            at com.iuconnect.iuconnectpro.activities.HomeActivity.onCreate(HomeActivity.java:31)
            at android.app.Activity.performCreate(Activity.java:5426)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by thomasdao** [comment]
This error is not related to Caldroid, you can find many answers on Stackoverlow

**Comment by justinvdk** [comment]
It does seem related though. I got the same issue and whenever I comment out this library from my dependencies the error occurs. Even before touching any code from the library.

**Comment by ssawchenko** [comment]
I am also getting this issue, however, applying the above suggestion (and deleting the build folder) does not appear to fix the issue for me. 

I believe this issue is Caldroid related (perhaps not at fault, but related for sure), as it appears immediately after I have adding the `compile 'com.roomorama:caldroid:3.0.1'` in my build script, without doing anything else further to my project. Removing the library from my build script results in the error disappearing again.

**Comment by andre719mv** [comment]
The reson of this issue is styles v11 and styles v14 xml files in project. 
There is lines:
<style name="AppBaseTheme" parent="android:Theme.Holo.Light">
<style name="AppBaseTheme" parent="android:Theme.Holo.Light.DarkActionBar">

My project use AppCompat themes.
Removing those lines fixed the issue.
