### ISSUE TITLE
how to remove calendar header

### ISSUE THREAD

**Issue by dieuhd** [roomorama/Caldroid#241]
I dont want show header. i try change layout but not working. Please help me. Thanks!

![68747470733a2f2f7261772e6769746875622e636f6d2f726f6f6d6f72616d612f43616c64726f69642f6d61737465722f73637265656e73686f742f312e706e67](https://cloud.githubusercontent.com/assets/3165692/6753119/1fee9e64-cf57-11e4-90b7-4b751785b88c.png)

**Comment by TheIronMarx** [comment]
```java
private static hideHeader(CaldroidFragment fragCalendar) {
   fragCalendar.getMonthTitleTextView().setVisibility(View.GONE);
   fragCalendar.getLeftArrowButton().setVisibility(View.GONE);
   fragCalendar.getRightArrowButton().setVisibility(View.GONE);
}
```

**Comment by dieuhd** [comment]
@TheIronMarx Thanks you!

**Comment by vigneswarandavarapu** [comment]
here i amusing this method i am getting null pointer exception....

**Comment by TheIronMarx** [comment]
Let me see that stacktrace

**Comment by vigneswarandavarapu** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Intent intent=getIntent();
         plan=intent.getIntExtra("plan", 0);
           click =intent.getBooleanExtra("click", false);
        //caldroidFragment =

/**/
        Bundle args = new Bundle();


        final Calendar cal = Calendar.getInstance();

        args.putInt(CaldroidFragment.MONTH, cal.get(Calendar.MONTH) + 1);
        args.putInt(CaldroidFragment.YEAR, cal.get(Calendar.YEAR));
        caldroidFragment.setArguments(args);
        caldroidFragment.setMaxDate(null);
       hideHeader(caldroidFragment);

        caldroidFragment.setMinDate(null);

               FragmentTransaction t = getSupportFragmentManager().beginTransaction();
        t.replace(R.id.calendar1, caldroidFragment);
        t.commit();

**Comment by MarHonny** [comment]
same problem

**Comment by TheIronMarx** [comment]
Same solution.

**Comment by MarHonny** [comment]
`  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        CaldroidFragment caldroidFragment = new CaldroidFragment();
        Bundle args = new Bundle();

        Calendar cal = Calendar.getInstance();
        args.putInt(CaldroidFragment.MONTH, cal.get(Calendar.MONTH) + 1);
        args.putInt(CaldroidFragment.YEAR, cal.get(Calendar.YEAR));

        caldroidFragment.setArguments(args);


        hideHeader(caldroidFragment);


        FragmentTransaction t = getSupportFragmentManager().beginTransaction();
        t.replace(R.id.calendar, caldroidFragment);
        t.commit();

        



    }

    private void hideHeader(CaldroidFragment fragCalendar) {
        fragCalendar.getMonthTitleTextView().setVisibility(View.GONE);
        fragCalendar.getLeftArrowButton().setVisibility(View.GONE);
        fragCalendar.getRightArrowButton().setVisibility(View.GONE);
    }`

> 
02-01 21:29:56.874 2352-2352/mh.smenovykalendararcelormittal20 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: mh.smenovykalendararcelormittal20, PID: 2352
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{mh.smenovykalendararcelormittal20/mh.smenovykalendararcelormittal20.MainActivity}: java.lang.NullPointerException
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                                  Caused by: java.lang.NullPointerException
                                                                                     at mh.smenovykalendararcelormittal20.MainActivity.hideHeader(MainActivity.java:53)
                                                                                     at mh.smenovykalendararcelormittal20.MainActivity.onCreate(MainActivity.java:39)
                                                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5146) 
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566) 
                                                                                     at dalvik.system.NativeStart.main(Native Method) 

>

**Comment by MarHonny** [comment]
Solved. Sorry for inconviences
