### ISSUE TITLE
Caldroid crashes on a Month or Year longClick

### ISSUE THREAD

**Issue by IcoWeb** [roomorama/Caldroid#267]
Hi, caldroid is great, I'm using it on one of my apps. I realized that it crashes when I perform a long click on the month's title or year. Any idea about why this is happening. Thanks in advance. 
Here is the error I'm getting:

android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:2928)
            at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2233)
            at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:2901)
            at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:2901)
            at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:3302)
            at android.widget.Editor$SelectionModifierCursorController.initHandles(Editor.java:3866)
            at android.widget.Editor$SelectionModifierCursorController.show(Editor.java:3837)
            at android.widget.Editor$SelectionActionModeCallback.onCreateActionMode(Editor.java:2851)
            at android.support.v7.internal.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:154)
            at android.support.v7.app.ActionBarActivityDelegateBase$ActionModeCallbackWrapper.onCreateActionMode(ActionBarActivityDelegateBase.java:1297)
            at android.support.v7.internal.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1012)
            at android.support.v7.internal.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:510)
            at android.support.v7.app.ActionBarActivityDelegateBase.startSupportActionMode(ActionBarActivityDelegateBase.java:581)
            at android.support.v7.app.ActionBarActivityDelegateHC.startActionModeForChild(ActionBarActivityDelegateHC.java:62)
            at android.support.v7.internal.widget.NativeActionModeAwareLayout.startActionModeForChild(NativeActionModeAwareLayout.java:44)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.View.startActionMode(View.java:4857)
            at android.widget.Editor.startSelectionActionMode(Editor.java:1558)
            at android.widget.Editor.performLongClick(Editor.java:890)
            at android.widget.TextView.performLongClick(TextView.java:8660)
            at android.view.View$CheckForLongPress.run(View.java:19723)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:2928)
            at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2233)
            at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:2901)
            at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:2901)
            at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:3302)
            at android.widget.Editor$SelectionModifierCursorController.initHandles(Editor.java:3866)
            at android.widget.Editor$SelectionModifierCursorController.show(Editor.java:3837)
            at android.widget.Editor$SelectionActionModeCallback.onCreateActionMode(Editor.java:2851)
            at android.support.v7.internal.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:154)
            at android.support.v7.app.ActionBarActivityDelegateBase$ActionModeCallbackWrapper.onCreateActionMode(ActionBarActivityDelegateBase.java:1297)
            at android.support.v7.internal.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1012)
            at android.support.v7.internal.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:510)
            at android.support.v7.app.ActionBarActivityDelegateBase.startSupportActionMode(ActionBarActivityDelegateBase.java:581)
            at android.support.v7.app.ActionBarActivityDelegateHC.startActionModeForChild(ActionBarActivityDelegateHC.java:62)
            at android.support.v7.internal.widget.NativeActionModeAwareLayout.startActionModeForChild(NativeActionModeAwareLayout.java:44)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:694)
            at android.view.View.startActionMode(View.java:4857)
            at android.widget.Editor.startSelectionActionMode(Editor.java:1558)
            at android.widget.Editor.performLongClick(Editor.java:890)
            at android.widget.TextView.performLongClick(TextView.java:8660)
            at android.view.View$CheckForLongPress.run(View.java:19723)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=15; index=1029
            at android.content.res.StringBlock.get(StringBlock.java:65)
            at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
            at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:967)
            at android.content.res.TypedArray.getString(TypedArray.java:176)
            at android.widget.TextView.<init>(TextView.java:1011)
            at android.widget.TextView.<init>(TextView.java:629)

**Comment by thomasdao** [comment]
This's probably bug in your program, the crash did not have anything from Caldroid
