### ISSUE TITLE
Caldroid not working in android 4.3 and 4.4.4 but 5.0.2 working fine

### ISSUE THREAD

**Issue by tutysathish** [roomorama/Caldroid#316]
Caldroid not working with android 4.3 (Samsung Galexy s III) and 4.4.4 (Emulator)
Error: 
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.humworld.healthypregnancytracker, PID: 5164
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.humworld.healthypregnancytracker/com.humworld.healthypregnancytracker.activity.AppointmentsActivity}: java.lang.RuntimeException: Binary XML file line #13: You must supply a layout_width attribute.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Binary XML file line #13: You must supply a layout_width attribute.
            at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
            at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5948)
            at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6117)
            at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java:1225)
            at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1062)
            at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:82)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:757)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1241)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5241)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mathif92** [comment]
I'm having the same problem.

I try to run my app on my Samsung Galaxy S4 and I could see the same Exception in Logcat.

Please, I would like to know whether it is possible to fix it or not.

**Comment by tutysathish** [comment]
I am not yet find out the solution... 
So I was switch over to another 3rd party calendar....

**Comment by pongpatr** [comment]
Workaround for now is using v2.1 instead

**Comment by tutysathish** [comment]
yup,
compile 'com.roomorama:caldroid:2.1.0' was working fine with Android 4.3 (Samsung Galaxy S3).
But Caldroid view is little bit differ from other versions.

**Comment by tutysathish** [comment]
asdasdads

**Comment by thomasdao** [comment]
Thanks for reporting this issue, it's fixed by upgrading support library to latest version.

**Comment by tutysathish** [comment]
Thanks thomasdao...
