### ISSUE TITLE
Error in Caldroid localInflater.inflate(R.layout.calendar_view, container, false)

### ISSUE THREAD

**Issue by sajadmaster** [roomorama/Caldroid#357]
I've downloaded Caldroid sample file and imported it to android studio. I've successfully built the sample project, however, when I want to run the project, I get the following error, which is related to Caldroid. Please fix this bug.

12-31 15:48:31.875 28179-28179/? E/AndroidRuntime: in writeCrashedAppName, pkgName :com.caldroidsample
12-31 15:48:31.875 28179-28179/? D/AndroidRuntime: file written successfully with content: com.caldroidsample StringBuffer : ;com.caldroidsample
12-31 15:48:31.875 28179-28179/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.caldroidsample, PID: 28179
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.caldroidsample/com.caldroidsample.CaldroidSampleActivity}: java.lang.RuntimeException: Binary XML file line #14: You must supply a layout_width attribute.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5021)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.RuntimeException: Binary XML file line #14: You must supply a layout_width attribute.
                                                       at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
                                                       at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5948)
                                                       at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6117)
                                                       at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1831)
                                                       at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1743)
                                                       at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:757)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                       at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1249)
                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1174)
                                                       at android.app.Activity.performStart(Activity.java:5241)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by Maragues** [comment]
I'm also seeing this crash every now and then

**Comment by Maragues** [comment]
@thomasdao I'm trying to debug this error. I've come across this answer http://stackoverflow.com/a/17730161/218473 that says that it may come from the <resources> node not defining the android namespace. Since it may not hurt, I'm doing a PR to add it and let's see if it fixes it, because I see this error quite often in an old device

**Comment by thomasdao** [comment]
@Maragues thanks for debugging this :). I found the issue in Android 4.x, somehow ContextThemeWrapper doesn't apply theme correctly when inflate calendar_view.xml. It can be fixed by adding ```getActivity().setTheme(themeResource)```. However I'm uncertain if this will have any negative impact on app that want to set theme dynamically.

**Comment by thomasdao** [comment]
@sajadmaster Please upgrade to Caldroid 3.0.0, it should fix this issue
