### ISSUE TITLE
Month is not in the range 1..12. Value is:0

### ISSUE THREAD

**Issue by ParitoshVaidya** [roomorama/Caldroid#358]
Caldroid crashes with following log

	hirondelle.date4j.DateTime$ItemOutOfRange: Month is not in the range 1..12. Value is:0
				at hirondelle.date4j.DateTime.checkRange(Unknown Source)
				at hirondelle.date4j.DateTime.validateState(Unknown Source)
				at hirondelle.date4j.DateTime.<init>(Unknown Source)
				at com.roomorama.caldroid.CaldroidFragment.setupDateGridPages(CaldroidFragment.java:1145)
				at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1123)
				at android.support.v4.app.Fragment.performCreateView(Fragment.java:1504)
				at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
				at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
				at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
				at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
				at android.support.v4.app.Fragment.performStart(Fragment.java:1525)
				at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:972)
				at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
				at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
				at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
				at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:450)
				at android.os.Handler.handleCallback(Handler.java:725)
				at android.os.Handler.dispatchMessage(Handler.java:92)
				at android.os.Looper.loop(Looper.java:137)
				at android.app.ActivityThread.main(ActivityThread.java:5283)
				at java.lang.reflect.Method.invokeNative(Native Method)
				at java.lang.reflect.Method.invoke(Method.java:511)
				at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
				at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
				at dalvik.system.NativeStart.main(Native Method)

**Comment by Nexen23** [comment]
Seems like you specified 0th month, but it must be in range of 1..12. What code do you use when getting such error?

**Comment by ParitoshVaidya** [comment]
Actually, I was working on maintenance code. In January month, app started crashing. So I added following hack in `retrieveInitialArgs()` of `CaldroidFragment.java`

```
if(month == 0) { 
    month = 1; 
}
```

Everything is working fine now (including month counts / display). I am not able to find Caldroid version in my code. But, my source code of `CaldroidFragment.java` is (much) different than current revision on Git.
