### ISSUE TITLE
java.lang.RuntimeException: Binary XML file line #14: You must supply a layout_width attribute.

### ISSUE THREAD

**Issue by GeekySingh** [roomorama/Caldroid#413]
I am using caldroid in one of my projects and it was working fine without any issue till yesterday.

Yesterday, crashlytics reported a crash in caldroid. Below is the logcat details:

```
Caused by java.lang.RuntimeException: Binary XML file line #14: You must supply a layout_width attribute.
       at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
       at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6314)
       at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6483)
       at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2043)
       at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1955)
       at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:61)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:757)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1257)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1989)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1989)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:598)
       at com.nagarro.reddoorz.reddoorz.ui.activity.BaseActivity.onStart(BaseActivity.java:133)
       at com.nagarro.reddoorz.reddoorz.ui.activity.MainActivity.onStart(MainActivity.java:138)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1187)
       at android.app.Activity.performStart(Activity.java:5409)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2507)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
       at android.app.ActivityThread.access$800(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5529)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Can you please tell me exactly what was the issue and how to fix it?

Thanks.

**Comment by RowlandOti** [comment]
Could you share your xml files too? That is where the problem could be first and foremost. @gaganpreet4423

**Comment by chathuralakmal** [comment]
Im also having this problem. i couldnt find the solution for it. im using gradle version 3.0.1

my XML file

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clickable="true"
    android:orientation="vertical" >

  <RelativeLayout
        android:id="@+id/error_text"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:orientation="horizontal"
         >

        <TextView
            android:id="@+id/error_textview"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:padding="10dp"
            android:layout_centerVertical="true"
            android:gravity="center"
            android:text="Please wait for attendance data gathering....."
            android:textColor="@color/black"
            android:textSize="18sp" />
    </RelativeLayout>

  <LinearLayout
        android:id="@+id/calendar1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical" >
    </LinearLayout>
</LinearLayout>
```

**Comment by dexion** [comment]
You may override any layout in your own project.

17 нояб. 2016 г. 11:10 пользователь "Chathura Lakmal" <
notifications@github.com> написал:
